//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugReporter_v2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public int BugId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Time { get; set; }
        public string Activity { get; set; }
    
        public virtual Bug Bug { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
